local ReplicatedStorage = game:GetService("ReplicatedStorage")

local PartyRoster = require(ReplicatedStorage.Shared.modules.PartyRoster)

return function()
	describe("PartyRoster", function()
		it("should start with just the leader, not ready", function()
			local roster = PartyRoster.new("Leader", 4)
			expect(roster:size()).to.equal(1)
			expect(roster:isLeader("Leader")).to.equal(true)
			expect(roster.ready["Leader"]).to.equal(false)
		end)

		it("should add members up to maxSize and reject beyond it", function()
			local roster = PartyRoster.new("Leader", 4)
			expect(roster:addMember("B")).to.equal(true)
			expect(roster:addMember("C")).to.equal(true)
			expect(roster:addMember("D")).to.equal(true)
			expect(roster:size()).to.equal(4)
			expect(roster:addMember("E")).to.equal(false)
			expect(roster:size()).to.equal(4)
		end)

		it("should reject adding a member who's already in the party", function()
			local roster = PartyRoster.new("Leader", 4)
			roster:addMember("B")
			expect(roster:addMember("B")).to.equal(false)
			expect(roster:size()).to.equal(2)
		end)

		it("should promote the earliest-joined remaining member when the leader leaves", function()
			local roster = PartyRoster.new("Leader", 4)
			roster:addMember("B")
			roster:addMember("C")
			local disbanded = roster:removeMember("Leader")
			expect(disbanded).to.equal(false)
			expect(roster:isLeader("B")).to.equal(true)
		end)

		it("should report disbanded (true) when the last member leaves", function()
			local roster = PartyRoster.new("Leader", 4)
			local disbanded = roster:removeMember("Leader")
			expect(disbanded).to.equal(true)
			expect(roster:size()).to.equal(0)
		end)

		it("should not change leadership when a non-leader member leaves", function()
			local roster = PartyRoster.new("Leader", 4)
			roster:addMember("B")
			roster:removeMember("B")
			expect(roster:isLeader("Leader")).to.equal(true)
			expect(roster:size()).to.equal(1)
		end)

		it("should report allReady only once every member is ready", function()
			local roster = PartyRoster.new("Leader", 4)
			roster:addMember("B")
			expect(roster:allReady()).to.equal(false)
			roster:setReady("Leader", true)
			expect(roster:allReady()).to.equal(false)
			roster:setReady("B", true)
			expect(roster:allReady()).to.equal(true)
		end)

		it("should ignore setReady for a non-member", function()
			local roster = PartyRoster.new("Leader", 4)
			roster:setReady("NotInParty", true)
			expect(roster.ready["NotInParty"]).to.equal(nil)
		end)
	end)
end
